namespace AspectSol.Lib.Domain.Tokenizer;

public enum TokenType
{
    Before = 1,
    After = 2,
    CallTo = 3,
    ExecutionOf = 4,
    OpenParenthesis = 5,
    CloseParenthesis = 6,
    Comma = 7,
    FullStop = 8,
    DoubleColon = 9,
    OpenDoubleSquareBrackets = 10,
    CloseDoubleSquareBrackets = 11,
    Wildcard = 12,
    TaggedWith = 13,
    ImplementingInterface = 14,
    NotSymbol = 15,
    AndSymbol = 16,
    OrSymbol = 17,
    Public = 18,
    Private = 19,
    Internal = 20,
    External = 21,
    Pure = 22,
    View = 23,
    ReturningTypes = 24,
    InInterface = 25,
    NotInInterface = 26,
    Get = 27,
    Set = 28,
    OpenSquareBrackets = 29,
    CloseSquareBrackets = 30,
    OriginatingFrom = 31,
    AddToDeclaration = 32,
    UpdateDefinition = 33,
    StringValue = 34,
    Number = 35,
    SequenceTerminator = 36,
    Invalid = 37,
    OpenScope = 38,
    CloseScope = 39,
    Address = 40,
    Aspect = 41,
    Scope = 42,
    ArbitraryWord = 43
}